### ISSUE TITLE
FAP Meeting STFC

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1043]
Issue we need to do for the meeting component:

- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1172
- [ ] https://github.com/isisbusapps/proposal-allocations/issues/356
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1019
- [ ] #963 
- [ ] #977 
- [ ] #1104 
- [ ] #1046
- [ ] #1052
- [ ] #1054
- [ ] #1049
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/1041
- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/965
- [x] #1105 
- [x] #1134 
- [x] #1044
- [x] #1048
- [x] #1050
- [x] #1051
- [x] #1045
- [x] #1047
- [x] #1053

### Need clarification

- [ ] https://github.com/UserOfficeProject/issue-tracker/issues/983
