### ISSUE TITLE
Migrate to new SMTP setup

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1108]
An epic to cover the issues involved in the migration of our services to the new SMTP setup.

- [x] https://github.com/isisbusapps/fap-results-letters/issues/133
- [x] https://github.com/isisbusapps/settings-tool/issues/274
- [x] https://github.com/isisbusapps/request-consumables/issues/29

These issues must be released by the July 15 deadline.

**Comment by joshhdawes** [comment]
https://github.com/isisbusapps/fap-results-letters/issues/133 only needs to go out before the next run of the results letters tool

**Comment by ACLay** [comment]
Looks like settings tool and request-consumables have both had their updates released. Fap results letters hasn't been released, so still contains a reference to the old server in code, but the bisappsetting value that overwrites that default in bisappsettings has been released, so I think we're good.

**Comment by joshhdawes** [comment]
@ACLay It would be good if we could release FAP results letters, so everything's consistent at the same time. That way, once we close this issue, we know that everything's been taken care of.

**Comment by joshhdawes** [comment]
FAP results letters release scheduled for 26/7/24.
