### ISSUE TITLE
Deploying FAP Reviews to LSF and Artemis

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1177]
This is an epic that contains issues/stories that will need to be addressed for FAP Reviews to be used by CLF during their calls.

- [x] https://github.com/UserOfficeProject/issue-tracker/issues/1227
- [x] https://github.com/UserOfficeProject/issue-tracker/issues/1228
- [x] https://github.com/UserOfficeProject/issue-tracker/issues/1229
- [x] #1332
- [x] https://github.com/UserOfficeProject/issue-tracker/issues/1238
- [x] https://github.com/UserOfficeProject/issue-tracker/issues/1312
- [x] https://github.com/isisbusapps/proposal-allocations/issues/621
- [x] #1336

**Comment by TCMeldrum** [comment]
Can we close this issue @joshhdawes
