### ISSUE TITLE
Import Xpress legacy proposals to prod

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1266]
Now that the development work is done for the legacy import (#87), we should run import legacy proposals to prod during the Xpress legacy freeze period.

Dev import issue: #1265

**Comment by simonfernandes** [comment]
## Pre import tasks:
- [x] Decide on what to do with duplicate legacy props: https://github.com/isisbusapps/proposal-submission/issues/1764
- [x] Double check with Emma that [instruments that only appear on legacy](https://github.com/UserOfficeProject/issue-tracker/issues/87#issuecomment-2417341926) are still being mapped to the same techniques, after techniques have been changed and finalised
- [x] Simon to run final test on local once techniques/instruments have been finalised.
- [x] Someone else (Deepak) to run final test on local once techniques/instruments have been finalised.
- [x] Ensure deleting a proposal cascades properly in the event of an issue.
- [x] Update prod API key with new permissions.
- [x] Create a new Xpress workflow for legacy calls that contains `QUICK_REVIEW` status but doesn't send any emails.
- [x] Check that the Xpress reference numbers to import aren't already being used in UOP. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575690424)
- [x] Remember to copy the terminal output as a reference.
- [x] Point the UOP and Xpress databases at prod in the `.env`
- [x] In the script parameters, make the reference numbers start at `1000000` to avoid [~6 digit reference numbers](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2580321292). Specify the new Xpress workflow in workflow parameter.


## Post import testing:
- [x] Check the number of legacy proposals imported is correct. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575671424)
- [x] Check all proposals have a technique and an instrument. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575671424)
- [x] Proposals should have the same instrument that they do on legacy. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575757499)
- [x] Where a legacy proposal is in an instrument that belongs to more than one technique, check that all techniques are assigned. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575757499)
- [x] Do spot checks to check that all proposals submitted before 1st Jan 2024 are either in 'Finished' or 'Unsuccessful' status. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575671424)
- [x] Do spot checks to check all proposals submitted from 2024 onwards have the correct status based on the mappings: https://github.com/UserOfficeProject/issue-tracker/issues/1138#issuecomment-2416465648 [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575757499)
- [x] Check that proposals are in the correct call by using the filter in the Xpress table and checking the submitted date.
- [x] Check distinct Xpress call names by using the filter in the Xpress table.
- [x] Check that there are no proposals in the wrong status by using the filters and query. [Query](https://github.com/UserOfficeProject/issue-tracker/issues/1266#issuecomment-2575757499)
- [x] Check that nothing is untoward by using the various filters/searching as a scientist and user officer.

## Post import tasks:
- [x] Update the Xpress calls for 2024 and 2025 to use a workflow that will send emails.
- [x] Update the Xpress calls for 2024 and 2025 so that the calls have instruments attached
- [x] Update the call configuration (reference number format, dates, etc.)
- [x] The reference number sequences needs updating/entering in the database for all existing 259xxxx proposals imported from legacy, so that when proposals are submitted on the new system, they continue on from the legacy sequence.
	- [x] Update the `proposal_sequence`  in the `call` table.
	- [x] Update the `reference_number_sequence` for all legacy 259xxxx proposals in the `proposals` table.
- [x] Remove retired or unavailable instruments from techniques. These shouldn't be available for scientists to assign. Retired instruments have `RETIRED` in their description. The two unavailable instruments are `Offspec` and `HRPD`. Note: any proposals that are already assigned to these instruments will display as having a blank instrument until https://github.com/UserOfficeProject/user-office-core/pull/943 is released.
- [x] Add back retired description to retired instruments SANS, MUON, QENS
- [x] Look into 1890275, 2190020, 2190149 no PI

**Comment by simonfernandes** [comment]
Script to show all imported proposals and their instruments, techniques and statuses (Postgres only):

```sql
SELECT p.proposal_pk,
       p.proposal_id,
       p.updated_at,
       p.submitted_date,
       ps."name" AS "status name",
       i."name" AS "inst name",
       STRING_AGG(t."name", ', ') AS "tech name(s)"
  FROM proposals p
  JOIN proposal_statuses ps ON ps.proposal_status_id = p.status_id
  JOIN technique_has_proposals thp ON thp.proposal_id = p.proposal_pk
  JOIN techniques t ON t.technique_id = thp.technique_id
  JOIN instrument_has_proposals ihp ON ihp.proposal_pk = p.proposal_pk
  JOIN instruments i ON i.instrument_id = ihp.instrument_id
  JOIN "call" c ON c.call_id = p.call_id
 WHERE c.call_short_code LIKE 'ISIS Xpress%'
 GROUP BY p.proposal_pk,
          p.proposal_id,
          p.updated_at,
          p.submitted_date,
          ps."name",
          i."name"
 ORDER BY p.proposal_id ASC
```

**Comment by simonfernandes** [comment]
Script to check that none of the Xpress reference numbers to import aren't already being used in UOP (Trino):

```sql
SELECT xp.reference_number
  FROM xpress_v4.xpress_v4.proposal xp
 INNER JOIN duo.public.proposals uop
    ON xp.reference_number = uop.proposal_id;
```

**Comment by simonfernandes** [comment]
Script to show all imported and legacy proposals and their instruments, techniques and statuses (Trino):

```sql
SELECT 
  uop.proposal_pk AS "UOP PK",
  uop.proposal_id AS "UOP proposal ID",
  leg.reference_number AS "Legacy ref num",
  uop.updated_at AS "UOP updated_at",
  uop.submitted_date AS "UOP submitted_date",
  COALESCE(leg.submitted_date, leg.modify_timestamp) AS "Legacy submission date",
  ps."name" AS "UOP status name",
  lps."name" AS "Legacy status name",
  i."name" AS "UOP inst name",
  li."name" AS "Legacy inst name",
  array_join(array_agg(t."name"), ', ') AS "tech names"
FROM duo.public.proposals uop
JOIN xpress_v4.xpress_v4.proposal leg ON leg.reference_number = uop.proposal_id
LEFT JOIN duo.public.proposal_statuses ps ON ps.proposal_status_id = uop.status_id
LEFT JOIN duo.public.technique_has_proposals thp ON thp.proposal_id = uop.proposal_pk
LEFT JOIN duo.public.techniques t ON t.technique_id = thp.technique_id
LEFT JOIN duo.public.instrument_has_proposals ihp ON ihp.proposal_pk = uop.proposal_pk
LEFT JOIN duo.public.instruments i ON i.instrument_id = ihp.instrument_id
LEFT JOIN xpress_v4.xpress_v4.proposal_status lps ON lps.id = leg.status_id
LEFT JOIN xpress_v4.xpress_v4.instrument li ON li.id = leg.instrument_id
JOIN duo.public."call" c ON c.call_id = uop.call_id
WHERE c.call_short_code LIKE 'ISIS Xpress%'
GROUP BY 
  uop.proposal_pk,
  uop.proposal_id,
  leg.reference_number,
  uop.updated_at,
  uop.submitted_date,
  COALESCE(leg.submitted_date, leg.modify_timestamp),
  ps."name",
  lps."name",
  i."name",
  li."name"
ORDER BY uop.proposal_id ASC;
```

**Comment by ACLay** [comment]
Just a thought around the UOP import, since any 6 digit or the shorter reference numbers might clash with the pre-submission auto-generated values, will they be left out of your initial import? I've got a design review next week for [renumbering old proposals with short reference numbers](https://github.com/isisbusapps/ISISBusApps/issues/964), and I wonder if it might be easier to wait to import the short ones until after that renumbering takes place?

**Comment by simonfernandes** [comment]
I had been planning to still import them because there are no clashes right now and there hopefully won't be in a few weeks time, and was planning to exclude any clashes at the time if there were.

But it's a good point that if the plan is to renumber all legacy 6-digit reference numbers then it may definitely be easier to just exclude them from this import. Because it sounds like the alternative would be to import them initially, then have to probably delete them all and re-import them with their new numbers at a later date.

I don't know how you would feel about excluding these @Cat-Lucifer? The six digit Xpress reference numbers go up to the beginning of 2011.

**Comment by Cat-Lucifer** [comment]
@simonfernandes @ACLay I'm happy for those pre-2011 proposals to be excluded and then imported at a later date.  If anybody needs that data / info then they'll just have to go through me or George.

**Comment by simonfernandes** [comment]
In case they're ever useful, these are logs of the 10 runs that were used in the import.

[Import script 01.txt](https://github.com/user-attachments/files/18884358/Import.script.01.txt)
[Import script 02.txt](https://github.com/user-attachments/files/18884354/Import.script.02.txt)
[Import script 03.txt](https://github.com/user-attachments/files/18884359/Import.script.03.txt)
[Import script 04 1000000-1500000.txt](https://github.com/user-attachments/files/18884361/Import.script.04.1000000-1500000.txt)
[Import script 05 1500000-1700000.txt](https://github.com/user-attachments/files/18884353/Import.script.05.1500000-1700000.txt)
[Import script 06 1700000-1900000.txt](https://github.com/user-attachments/files/18884355/Import.script.06.1700000-1900000.txt)
[Import script 07 1900000-2100000.txt](https://github.com/user-attachments/files/18884356/Import.script.07.1900000-2100000.txt)
[Import script 08 1900000-2100000.txt](https://github.com/user-attachments/files/18884357/Import.script.08.1900000-2100000.txt)
[Import script 09 2100000-2300000.txt](https://github.com/user-attachments/files/18884360/Import.script.09.2100000-2300000.txt)
[Import script 10 2300000-99999999.txt](https://github.com/user-attachments/files/18884352/Import.script.10.2300000-99999999.txt)
