### ISSUE TITLE
SEP/FAP integration for STFC for 2024_2 (March 2024)

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#961]
Parent Issue for tracking what needs to be done to get FAPs ready for STFC no specific ordering and some have some crossover:

Round open:

- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/954
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/953
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/878
- [ ] https://github.com/isisbusapps/proposal-allocations/issues/356
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/910
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/877
- [x] #969
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/962
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/967
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/966
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/974
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/978
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/979
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/980
- [x] #973
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/984
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/987
- [x] Reviewers cannot see each other comments - This is already the case

Round Close
- [x] https://github.com/isisbusapps/reporting-tool/issues/746
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/968
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/981
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/988

Nice to have:
- [x] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/982
- [x] #996

Not needed:
- [ ] #963
- [x] ~https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/964~ Will be done manually 
- [x] ~https://github.com/isisbusapps/panel-member-manager/issues/54~ The rest API went out earlier then expected
- [x] ~https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/965~ Will be done manually this round
- [ ] https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/983
